# Generated by Django 3.2.5 on 2021-12-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myitems', '0003_auto_20211202_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandcategory',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='url',
            new_name='slug',
        ),
    ]
